### ISSUE TITLE
Code never get compiled 

### ISSUE THREAD

**Issue by xfinitysoft** [m-Ryan/easy-email-demo#1]
Hi Ryan 

Detail email of issues has been sent to your email address:
m-ryan@foxmail.com

Opening this issue so this can help everyone else who is using this.
Platform Windows 8.

Executing Command : npm run dev
server started, on visiting localhost:3000 

Got lot of errors in console.
Error File has been attached.
[easy-email-demo-error-log.txt](https://github.com/m-Ryan/easy-email-demo/files/6910073/easy-email-demo-error-log.txt)

If I run this command :
npm run build 

Then around 32 error are found.
code never got compiled and never able to seen the results.

Log of error on running npm run build is:
@/typing module cant be found 
@/constant module cant be found 

So where ever you used @/ to important the file , import is not working.
moreover MjmlBlockItem is also not found in Mjmltojson.d.ts file .

I resolved errors of @/typing by adding path object in tsconfig file but 
MjmlBlockItem still not works.

if i delete the code of MjmlBlockItem in Mjmltojson.d.ts.

Build has been generated.

When i try to run the the command 
npm run serve 

serve is started but still nothing to see on the screen .

lot of error in console.

Is it possible if you can push the latest code and try to compile it on window operating system and see if it works at all.
Looking forward to your kind reply.
Thank You

**Comment by m-Ryan** [comment]
![image](https://user-images.githubusercontent.com/20615214/127759067-f7dec5cb-0d35-4cb2-aa1a-e513d244f1e2.png)

It has been solved.
