### ISSUE TITLE
what is the correct way to make a <RadioGroup> in a Custom Block Panel

### ISSUE THREAD

**Issue by Frankosntin** [m-Ryan/easy-email-demo#13]
hi, im a newbie in react and im customizing the easy-email-demo with some custom blocks. Im trying to make a multi language footer with a radio option in the panel to change the text inside the footer to preset values. The problem is that i dont know how to properly declare the RadioGroup component .

That is how im doing:

` 
<RadioGroup
              options={
              value:"value 1",
              label:"value 1",
              }
              name={'${focusIdx}.data.value.footer-language'}
              vertical
            />`

but it returns an error : Cannot find name 'value'. Did you mean 'values'?

how do i declare the options of my radio button?

sorry about this dummy question but im stuck in this for days...

**Comment by m-Ryan** [comment]
changes
```tsx
<RadioGroup options={[{ value:"value 1", label:"value 1", } ]} name={'${focusIdx}.data.value.footer-language'} vertical />
```

**Comment by Frankosntin** [comment]
thanks ! the Radio Group declaration is now working, but the app gives me a importation error now
![image](https://user-images.githubusercontent.com/67793277/177369573-b81a0997-ef7b-4772-8e5f-c9b03e05438d.png)

**Comment by Frankosntin** [comment]
> thanks ! the Radio Group declaration is now working, but the app gives me a importation error now ![image](https://user-images.githubusercontent.com/67793277/177369573-b81a0997-ef7b-4772-8e5f-c9b03e05438d.png)

I solved the importation problem by importing the RadioGroupField  component instead RadioGroup!

Thanks for the support @m-Ryan
