### ISSUE TITLE
Updating the demo version.

### ISSUE THREAD

**Issue by thefubon** [m-Ryan/easy-email-demo#3]
Tell me please. Can you implement this idea for your easy-email-demo. It is enough for me to store templates on my local computer. It was very convenient and safe. Some emails for personal mailing to clients. And managers don't know how to use MJML. But they could upload images and templates from local computer to web application. just for editing capability? That was very cool.

![easy-email](https://user-images.githubusercontent.com/43171309/131650873-f5b00819-1b29-4dd2-b3b9-29170141839a.png)

**Comment by m-Ryan** [comment]
Thanks for your feedback, I will update the demo later. And I will write a document later on how to create and use a test account.

**Comment by m-Ryan** [comment]
Demo updated. @thefubon

**Comment by thefubon** [comment]
I'm shocked! You are a genius.

**Comment by thefubon** [comment]
There is another question. It is possible to add pictures to the path of the faceup. button to add from the computer
![Upload](https://user-images.githubusercontent.com/43171309/131704802-6bfcd85f-3f5b-4875-8932-1aab83a8635e.png)

**Comment by thefubon** [comment]
Is it possible to edit these blocks? 
![Снимок экрана 2021-09-01 в 19 52 56](https://user-images.githubusercontent.com/43171309/131712225-126c56b9-f71e-4eb0-aded-f12b236366c6.png)

**Comment by m-Ryan** [comment]
> There is another question. It is possible to add pictures to the path of the faceup. button to add from the computer
> ![Upload](https://user-images.githubusercontent.com/43171309/131704802-6bfcd85f-3f5b-4875-8932-1aab83a8635e.png)

You need to have an api from back-end before you want to upload.

**Comment by m-Ryan** [comment]
> Is it possible to edit these blocks?
> ![Снимок экрана 2021-09-01 в 19 52 56](https://user-images.githubusercontent.com/43171309/131712225-126c56b9-f71e-4eb0-aded-f12b236366c6.png)

You cannot edit basic blocks, but you can add custom blocks.
