### ISSUE TITLE
Custom Block ( Product Recommendation ) Development

### ISSUE THREAD

**Issue by xfinitysoft** [m-Ryan/easy-email-demo#5]
Customizations and Further Development

Due to lack of proper documentation, Need help regarding Custom Block development
Below is the list of task :

1. 
How in Custom Block accordion can be added to group Data accordingly :
Want to add accordion in the highlighted area to group data, check the screenshot : https://i.imgur.com/t06x6eH.png

2.
Custom block you have added ( Product recommendation ) 
How to reduce and increase row and columns from Product recommendation attributes area?
To make it dynamic so users can increase and decrease rows and columns in editor.

3.
How to display and hide the content of custom block ( Product recommendation )

4.
How to add custom input fields and libraries like select2 to fetch data from server and show in the editor on selection

5.
How to add identified in Editor blocks ( Custom Blocks ) so Email could be made dynamic and identifier can be replaced on backend Side with dynamic data during sending an email?

6.
How to get changes of custom block attributes inside the custom block ( as an event listener ) 

Rest of detail has been provided over email.
Make the Changes in both demo and easy email repository as well.

Looking forward to your quick response.
Thank you

**Comment by m-Ryan** [comment]
### 1.Defined your custom filed, please see ` src\components\core\Form\Input.tsx`


### 2.
![image](https://user-images.githubusercontent.com/20615214/131994163-6e5df545-8a62-4fb4-9003-e8426026f75c.png)

### In  `transform`method, You can get your custom block attributes . As follows, you only need change productList's length

```ts
 {productList.map((item, index) => (
            <Column
              key={index}
              padding='0px'
              border='none'
              vertical-align='top'
            >
              <Image
                align='center'
                height='auto'
                padding='10px'
                width='150px'
                src={item.image}
              />
            </Column>
          ))}
```

### 3. See 2, write if-else in your  `transform` method.


### 4. Defined your custom filed, please see ` src\components\core\Form\Input.tsx`


### 5. Find your custom block, and then replace the default value, like
![image](https://user-images.githubusercontent.com/20615214/131996166-d7d5982f-3d75-442c-9a2f-554b2a20bcd8.png)
![image](https://user-images.githubusercontent.com/20615214/131996247-a714236b-f6a6-4e1a-b535-7476f02e0a32.png)


### 6. See `https://final-form.org/docs/react-final-form/api/useField`
```ts
    import { FieldProps, useField, useForm } from 'react-final-form';
    const { focusIdx } = useFocusIdx();
    const {
      input: { value, onBlur },
      meta: { touched, error },
    } = useField(focusIdx);

```
