### ISSUE TITLE
Add downloading pictures from a local folder

### ISSUE THREAD

**Issue by thefubon** [m-Ryan/easy-email-demo#7]
You can add the ability to add pictures to the test, as well as in easy-mail I upload a picture but it is stored in a folder. After I export the template to a folder with pictures they will always be available locally.

And even cooler is through ftp.json to connect the upload to your FTP.
That would be perfect. 

<img width="662" alt="Снимок экрана 2021-10-06 в 00 48 35" src="https://user-images.githubusercontent.com/43171309/136108053-7863eda7-f8d9-4f07-92c5-1fe448e91474.png">

**Comment by m-Ryan** [comment]
![image](https://user-images.githubusercontent.com/20615214/136139607-b9ea94ec-8af0-442b-a68b-103da496a819.png)

![image](https://user-images.githubusercontent.com/20615214/136139628-4fa458cc-57e6-4b0d-9258-6e8dfdfd15d0.png)

It's easy, try to add images to  public directory.

**Comment by thefubon** [comment]
The site is in production and there is no access to the folder

**Comment by m-Ryan** [comment]
Can not  deploy access  folder to production ?

**Comment by thefubon** [comment]
I have access. But I installed it for another person. He doesn't have
access to the server. That's why it would be cool. Upload pictures directly
to the folder without using asw.


Ср, 6 окт. 2021 г. в 08:37, Ryan ***@***.***>:

**Comment by m-Ryan** [comment]
I think the only one way is upload local picture to your server. Upload picture and write  to the access floder
